import React,{useEffect,useMemo,useRef,useState} from 'react';
import {RobotViewer} from './viewer.js';
import {parseRecording,atTime,stats} from './telemetry.js';
import {errorSeries,clampRange} from './timeline.js';
import {AnalysisPlot,Overview,number,traceStyles} from './AnalysisPlot.jsx';
import './telemetry.css';

const groupNames={q:'Joint position',dq:'Joint velocity',tau:'Joint effort',FT:'Force / torque',Timing:'Command timing'};
function download(text,name,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Splitter({onChange,vertical=false}){const drag=useRef(null);return <div role="separator" aria-label={vertical?'Resize model':'Resize inspector'} className={`ax-splitter ${vertical?'horizontal':''}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current=vertical?e.clientY:e.clientX;}} onPointerMove={e=>{if(drag.current==null)return;const now=vertical?e.clientY:e.clientX;onChange(now-drag.current);drag.current=now;}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>;}

export function TelemetryAnalysis({identity}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[time,setTime]=useState(0),[hover,setHover]=useState(null);
  const [playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[loop,setLoop]=useState(false),[stepBy,setStepBy]=useState('robot');
  const [range,setRange]=useState([0,1]),[selection,setSelection]=useState(null),[cursors,setCursors]=useState({A:null,B:null}),[mode,setMode]=useState('seek');
  const [traces,setTraces]=useState({measured:true,command:true,error:false}),[hidden,setHidden]=useState([]),[collapsed,setCollapsed]=useState([]),[selected,setSelected]=useState('q0'),[markers,setMarkers]=useState([]);
  const [panelWidth,setPanelWidth]=useState(350),[modelHeight,setModelHeight]=useState(250),[ready,setReady]=useState(false);
  const host=useRef(null),viewer=useRef(null),raw=useRef(''),lanes=useRef(null);
  const [gutter,setGutter]=useState(0);
  useEffect(()=>{const el=lanes.current;const observer=new ResizeObserver(()=>setGutter(el.offsetWidth-el.clientWidth));observer.observe(el);return()=>observer.disconnect();},[]);
  const duration=data?.duration||1;
  function load(text){try{const next=parseRecording(text);next.tracks=next.tracks.map(t=>({...t,error:errorSeries(t.points,t.commanded)}));raw.current=text;setData(next);setTime(next.robot[0]?.t||0);setRange([0,next.duration]);setSelection(null);setCursors({A:null,B:null});setMarkers([]);setHidden([]);setCollapsed([]);setPlaying(false);setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{if(!identity||identity==='1')return;let active=true;fetch(`/api/recordings/${encodeURIComponent(identity)}/download`).then(r=>{if(!r.ok)throw Error(`Recording could not load (${r.status})`);return r.text();}).then(t=>{if(active)load(t);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[identity]);
  useEffect(()=>{try{viewer.current=new RobotViewer(host.current,()=>setReady(true),e=>setError(e));}catch(e){setError(e.message);}return()=>viewer.current?.dispose();},[]);
  const robotSeries=useMemo(()=>data?.robot.map(r=>[r.t,r])||[],[data]);
  const commands=useMemo(()=>data?.attempted.map(r=>[r.t,r])||[],[data]);
  const positions=useMemo(()=>data?.attempted.filter(r=>r.values.position?.length===7).map(r=>[r.t,r.values.position])||[],[data]);
  useEffect(()=>{const state=atTime(robotSeries,time)?.[1];if(viewer.current?.robot)viewer.current.robot.visible=traces.measured&&state?.values.positions?.length===7;if(state?.values.positions?.length===7)viewer.current?.update({robot:state.values,gripper:state.values.gripper});viewer.current?.setPreview(traces.command?atTime(positions,time)?.[1]:null);},[robotSeries,positions,time,ready,traces]);
  const playbackRange=selection&&selection[1]>selection[0]?selection:range;
  useEffect(()=>{if(!playing||!data)return;let frame,last=performance.now();const tick=now=>{const dt=(now-last)/1000*speed;last=now;setTime(t=>{if(t+dt>=playbackRange[1]){if(loop)return playbackRange[0];setPlaying(false);return playbackRange[1];}return Math.max(playbackRange[0],t+dt);});frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,speed,loop,data,playbackRange]);
  function seek(t){setPlaying(false);setTime(Math.max(0,Math.min(duration,t)));}
  function step(dir){const rows=stepBy==='robot'?data?.robot:data?.attempted;if(!rows)return;const row=dir>0?rows.find(r=>r.t>time+1e-9):[...rows].reverse().find(r=>r.t<time-1e-9);const t=row?.t??(dir>0?duration:0);seek(t);if(t<range[0]||t>range[1])setRange(clampRange(t-(range[1]-range[0])/2,range[1]-range[0],duration));}
  function play(){if(time>=playbackRange[1]||time<playbackRange[0])setTime(playbackRange[0]);setPlaying(p=>!p);}
  useEffect(()=>{function key(e){if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();play();}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key.toLowerCase()==='a')setCursors(c=>({...c,A:time}));if(e.key.toLowerCase()==='b')setCursors(c=>({...c,B:time}));}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[time,data,stepBy,range,playbackRange]);
  const current=data?.tracks.find(t=>t.id===selected),inspection=hover??time;
  const sensorSeries=useMemo(()=>data?.ft.map(r=>[r.t,r])||[],[data]);
  const command=atTime(commands,inspection)?.[1],sample=atTime(current?.group==='FT'?sensorSeries:robotSeries,inspection)?.[1];
  const ack=command&&data.commands.find(r=>r.stage==='acknowledged'&&r.run_id===command.run_id&&r.sample_index===command.sample_index);
  const events=useMemo(()=>[...(data?.rows.filter(r=>r.type==='event')||[]),...markers].sort((a,b)=>a.t-b.t),[data,markers]);
  const statisticsRange=selection&&selection[1]>selection[0]?selection:range;
  function exportCSV(){const rows=['time_s,channel,trace,value'];for(const track of data.tracks)for(const [kind,points] of [['measured',track.points],['command_sent',track.commanded],['error_measured_minus_sent',track.error]])for(const [t,v]of points)if(t>=statisticsRange[0]&&t<=statisticsRange[1])rows.push(`${t},${track.id},${kind},${v}`);download(rows.join('\n'),'telemetry-range.csv');}
  function toggle(id){setHidden(h=>h.includes(id)?h.filter(x=>x!==id):[...h,id]);}
  return <div className="ax-app">
    <div className="ax-header"><div className="ax-brand">s<span>sawyer / <b>analysis</b></span></div><div className="ax-session"><b>{data?.meta.name||'Telemetry analysis'}</b><small>{data?`${data.robot.length} robot frames · ${data.ft.length} sensor frames · ${data.complete?'Finalized':'Incomplete recording'}`:'Open a recording to begin'}</small></div><label className="ax-button">Open recording<input hidden type="file" accept=".jsonl,.ndjson" onChange={e=>e.target.files[0]?.text().then(load)}/></label><button disabled={!data} onClick={()=>download(raw.current,'recording.jsonl','application/x-ndjson')}>Save original</button><button disabled={!data} onClick={exportCSV}>Export selection</button></div>
    {error&&<div role="alert" className="ax-alert">{error}</div>}
    <div className="ax-workspace" style={{gridTemplateColumns:`190px minmax(240px,1fr) 7px ${panelWidth}px`}}>
      <nav className="ax-channels"><h3>Channels <button onClick={()=>setHidden([])}>Show all</button></h3>{Object.entries(groupNames).map(([group,label])=><div className="ax-channel-group" key={group}><b>{label}</b>{data?.tracks.filter(t=>t.group===group).map(t=><label key={t.id} className={selected===t.id?'selected':''}><input type="checkbox" checked={!hidden.includes(t.id)} onChange={()=>toggle(t.id)}/><button onClick={()=>setSelected(t.id)}>{t.label}<small>{t.unit}</small></button></label>)}</div>)}</nav>
      <section className="ax-editor"><div className="ax-toolbar">{[['seek','Playhead'],['pan','Pan'],['select','Select range'],['A','Cursor A'],['B','Cursor B']].map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{label}</button>)}<button onClick={()=>setRange([0,duration])}>Fit all</button><button disabled={!selection||selection[1]<=selection[0]} onClick={()=>setRange([...selection])}>Fit selection</button></div>
        <div className="ax-legend">{Object.entries(traceStyles).map(([key,s])=><label key={key}><input type="checkbox" checked={traces[key]} onChange={e=>setTraces(t=>({...t,[key]:e.target.checked}))}/><i style={{borderColor:s.color,borderTopStyle:key==='measured'?'solid':key==='command'?'dashed':'dotted'}}/>{s.name}</label>)}</div>
        <div className="ax-overview-label"><span>SESSION OVERVIEW · J0 position</span><span>{duration.toFixed(4)} s</span></div><Overview data={data} range={range} setRange={setRange} time={time}/>
        <div className="ax-ruler" style={{paddingRight:gutter}}><span>CHANNEL</span><div>{Array.from({length:5},(_,i)=><span key={i}>{(range[0]+(range[1]-range[0])*i/4).toFixed(4)} s</span>)}</div></div>
        <div className="ax-event-row" style={{paddingRight:gutter}}><span>EVENTS</span><div>{events.filter(e=>e.t>=range[0]&&e.t<=range[1]).map((e,i)=><button key={i} style={{left:`${(e.t-range[0])/(range[1]-range[0])*100}%`}} title={`${e.t.toFixed(5)} s · ${e.event}`} onClick={()=>seek(e.t)}>◆</button>)}</div></div>
        <div className="ax-tracks" ref={lanes}>{Object.entries(groupNames).map(([group,label])=><React.Fragment key={group}><button className="ax-group-title" onClick={()=>setCollapsed(c=>c.includes(group)?c.filter(g=>g!==group):[...c,group])}>{collapsed.includes(group)?'▸':'▾'} {label}<small>{group}</small></button>{!collapsed.includes(group)&&data?.tracks.filter(t=>t.group===group&&!hidden.includes(t.id)).map(track=><AnalysisPlot key={track.id} {...{track,range,setRange,duration,time,seek,cursors,setCursors,selection,setSelection,mode,traces,hover,setHover}} onSelect={setSelected} selected={selected===track.id}/>)}</React.Fragment>)}</div>
        <div className="ax-hint">Wheel: zoom at pointer · Shift-wheel: pan · Drag: selected tool · Double-click: fit all</div>
      </section><Splitter onChange={delta=>setPanelWidth(w=>Math.max(280,Math.min(650,w-delta)))}/>
      <section className="ax-inspector"><div className="ax-panel-title">Recorded robot <span>solid: measured · blue ghost: sent</span></div><div className="ax-model" style={{height:modelHeight}} ref={host}/><Splitter vertical onChange={d=>setModelHeight(h=>Math.max(140,Math.min(550,h+d)))}/><div className="ax-camera">{['Perspective','Front','Top'].map(v=><button key={v} onClick={()=>viewer.current?.view(v)}>{v}</button>)}<button onClick={()=>viewer.current?.fit()}>Fit</button></div>
        <div className="ax-inspector-scroll"><h3>{current?`${groupNames[current.group]} / ${current.label}`:'Signal inspector'} <small>{current?.unit}</small></h3><div className="ax-inspect-time">{hover==null?'Playhead':'Pointer'} {inspection.toFixed(6)} s</div>
          <table><thead><tr><th>Trace</th><th>Value</th></tr></thead><tbody>{[['measured',current?.points],['command',current?.commanded],['error',current?.error]].map(([key,points])=><tr key={key}><td style={{color:traceStyles[key].color}}>{traceStyles[key].name}</td><td>{number(atTime(points||[],inspection)?.[1])}</td></tr>)}</tbody></table>
          <h3>A/B comparison <button onClick={()=>setCursors({A:null,B:null})}>Clear</button></h3><div className="ax-ab">{['A','B'].map(key=><label key={key}>{key}<input type="number" step=".001" min="0" max={duration} placeholder="Unset" value={cursors[key]??''} onChange={e=>setCursors(c=>({...c,[key]:e.target.value===''?null:Math.max(0,Math.min(duration,+e.target.value))}))}/><button onClick={()=>setCursors(c=>({...c,[key]:time}))}>At playhead</button></label>)}</div><p>Δt (B − A): {cursors.A!=null&&cursors.B!=null?number(cursors.B-cursors.A):'—'} s</p>
          <table><thead><tr><th>Trace</th><th>A</th><th>B</th><th>Δ value</th></tr></thead><tbody>{[['Measured',current?.points],['Sent',current?.commanded],['Error',current?.error]].map(([name,points])=>{const a=cursors.A==null?undefined:atTime(points||[],cursors.A)?.[1],b=cursors.B==null?undefined:atTime(points||[],cursors.B)?.[1];return <tr key={name}><td>{name}</td><td>{number(a)}</td><td>{number(b)}</td><td>{number(a==null||b==null?undefined:b-a)}</td></tr>;})}</tbody></table>
          <h3>{selection?'Selection':'Visible range'} statistics <button onClick={()=>setSelection(null)}>Clear selection</button></h3><p>{statisticsRange.map(t=>t.toFixed(5)).join(' → ')} s</p><table><thead><tr><th>Trace</th><th>Min</th><th>Max</th><th>RMS</th></tr></thead><tbody>{[['Measured',current?.points],['Sent',current?.commanded],['Error',current?.error]].map(([name,points])=>{const s=stats(points||[],...statisticsRange);return <tr key={name} title={`Samples: ${s?.n||0}; mean: ${number(s?.mean)}`}><td>{name}</td><td>{number(s?.min)}</td><td>{number(s?.max)}</td><td>{number(s?.rms)}</td></tr>;})}</tbody></table>
          <details open><summary>Sample & command details</summary><dl><dt>State received</dt><dd>{sample?`${sample.t.toFixed(6)} s`:'—'}</dd><dt>State sequence</dt><dd>{sample?.sequence??'—'}</dd><dt>Source timestamp (ns)</dt><dd>{sample?.clock.source_time_ns??'—'}</dd><dt>Command sample</dt><dd>{command?.sample_index??'—'}</dd><dt>Run</dt><dd>{command?.run_id??'—'}</dd><dt>Scheduled</dt><dd>{command?`${((command.scheduled_monotonic_ns-data.meta.clock.monotonic_ns)/1e9).toFixed(6)} s`:'—'}</dd><dt>Sent</dt><dd>{command?`${command.t.toFixed(6)} s`:'—'}</dd><dt>Acknowledged</dt><dd>{ack?`${ack.t.toFixed(6)} s · ${ack.success?'accepted':'rejected'}`:'—'}</dd><dt>Round trip</dt><dd>{ack?`${((ack.t-command.t)*1000).toFixed(3)} ms`:'—'}</dd></dl></details>
          <details><summary>Events & markers ({events.length})</summary><button disabled={!data} onClick={()=>setMarkers(m=>[...m,{t:time,event:`Marker ${m.length+1}`}])}>Add marker at playhead</button>{events.map((e,i)=><button className="ax-event" key={i} onClick={()=>seek(e.t)}>{e.t.toFixed(5)} s · {e.event}<small>{e.data?.reason||''}</small></button>)}</details>
          <details><summary>Signal interpretation</summary><p>Command sent is the attempted bridge command. Error is measured minus the most recent sent value at each measured sample; it is unavailable before the first command. It does not correct transport delay.</p><p>Streams align on operations' monotonic receipt clock. Replay holds measured samples. Acknowledgement is not proof of physical execution. Markers are temporary. CSV includes measured, sent and error samples in the selection.</p></details>
        </div>
      </section>
    </div>
    <div className="ax-transport"><button disabled={!data} onClick={()=>seek(0)}>│◀</button><button disabled={!data} onClick={()=>step(-1)}>Previous</button><button disabled={!data} className="ax-play" onClick={play}>{playing?'Pause':'Play'}</button><button disabled={!data} onClick={()=>step(1)}>Next</button><select aria-label="Step by" value={stepBy} onChange={e=>setStepBy(e.target.value)}><option value="robot">Robot samples</option><option value="command">Command events</option></select><strong>{time.toFixed(5)} <small>/ {duration.toFixed(5)} s</small></strong><input aria-label="Playhead" type="range" min="0" max={duration} step=".00001" value={time} onChange={e=>seek(+e.target.value)}/><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.1,.25,.5,1,2,4].map(v=><option key={v} value={v}>{v}×</option>)}</select><label><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/>Loop {selection?'selection':'view'}</label></div>
  </div>;
}
